server:
  ip: 172.16.100.104
  port: 8888
logging:
  file: wechat-server.log
spring:
  datasource:
    url: jdbc:mysql://172.16.100.145:20113/iot
    username: root
    password: nAb5k1A5951C
    driver-class-name: org.mariadb.jdbc.Driver
    druid:
        web-stat-filter:
          enabled: false
        stat-view-servlet:
          enabled: false
        test-while-idle: false
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
# 配置API网关
kong:
  # 配置kong的管理地址和代理地址
  adminUrl: http://172.16.100.145:20111/
  proxyUrl: http://172.16.100.145:20110/
  # 配置服务，每个子系统作为一个独立的服务
  serviceName: service.wechat
  serviceUrl: http://service.wechat/
  # 配置当前服务下的所有路由，路由就是URL规则，正常一个子系统一个路由即可，如果配置不同的插件，需要拆开
  routes:
      # 除登录之外的API，都需要jwt认证，这里统一配置，多个插件用逗号拆分
      # 登录不需要进行jwt校验，单独列出
    - path: /api/login
      plugin:
    - path: /api/chat
      plugin: jwt
    - path: /srv/chat
      plugin:
  # 配置上游服务，和service一致，用来实现负载均衡和健康检查
  upstreamName: ${kong.serviceName}
  # 健康检查的相关配置
  healthCheckPath: /
  healthCheckConcurrency: 10
  healthCheckTimeout: 5
  healthCheckHealthyInterval: 3
  healthCheckHealthySuccesses: 1
  healthCheckUnhealthyInterval: 5
  healthCheckUnhealthyTimeouts: 1
  target: ${server.ip}:${server.port}